# Generated by Django 2.1.7 on 2019-03-15 00:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('gonderen_email', models.CharField(max_length=50)),
                ('gonderi_tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('derskodu', models.CharField(max_length=20)),
                ('yariyil', models.IntegerField()),
                ('türü', models.CharField(choices=[('z', 'Zorunlu'), ('s', 'Seçmeli')], max_length=20)),
                ('ders_text', models.TextField(default='Ders')),
            ],
            options={
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='Egitmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unvan_ve_isim', models.CharField(max_length=100)),
                ('isim', models.CharField(max_length=50)),
                ('soyisim', models.CharField(max_length=50)),
                ('unvan', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Eğitmenler',
            },
        ),
        migrations.CreateModel(
            name='Gonderi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('dosya', models.FileField(blank=True, null=True, upload_to='files')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gonderiler.Ders')),
                ('egitmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gonderiler.Egitmen')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('follows', models.ManyToManyField(related_name='followed_by', to='gonderiler.Ders')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='gonderi',
            name='yazar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gonderiler.User'),
        ),
    ]
