# Generated by Django 2.1.7 on 2019-03-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonderiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('duyuru_tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
