# Generated by Django 2.1.7 on 2019-03-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonderiler', '0002_duyurular'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='okul_no',
            field=models.IntegerField(default=14504169, max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
